from src.models.deck import Deck
from src.models.faction import Faction
from src.genetic.models.rule import Rule, create_random_rule
import pandas as pd
import random
import copy


class RuleSet:
    def __init__(self, rules: list[Rule]):
        self.rules = rules

    def __len__(self):
        return len(self.rules)

    def apply(self, deck: Deck, card_pool: pd.DataFrame) -> tuple[Deck, int]:
        new_deck = Deck(
            leader_ability=deck.leader_ability,
            stratagem=deck.stratagem,
            cards=deck.cards.copy(),
            faction=deck.faction,
        )

        applied_count = 0
        for rule in self.rules:
            if rule.apply(new_deck, card_pool):
                applied_count += 1

        return new_deck, applied_count

    def __repr__(self):
        rules_preview = ",\n  ".join(repr(rule) for rule in self.rules[:5])
        more = f", ... (+{len(self.rules) - 5} more)" if len(self.rules) > 5 else ""
        return f"<RuleSet with {len(self.rules)} rules: [\n  {rules_preview}{more}\n]>"

    def mutate(
        self,
        card_pool: pd.DataFrame,
        factions: list[Faction],
        stratagems: list,
        impact=0.1,
    ):
        new_rules = []
        all_card_ids = list(card_pool.index)

        for rule in self.rules:
            r = random.random()
            if r < impact / 10:
                new_rule = create_random_rule(card_pool, factions, stratagems)
                new_rules.append(new_rule)
            elif r < impact:
                rule = copy.deepcopy(rule)
                mutate_type = random.choice(["has_card", "leftover_provision_min"])

                if mutate_type == "has_card":
                    has_cards = rule.conditions.get("has_card")

                    if has_cards is None:
                        rule.conditions["has_card"] = (random.choice(all_card_ids),)
                    else:
                        if not isinstance(has_cards, (list, tuple)):
                            has_cards = (has_cards,)

                        has_cards = list(has_cards)
                        mutation_type = random.choice(["add", "remove", "replace"])

                        if mutation_type == "add" and len(has_cards) < 5:
                            candidates = [cid for cid in all_card_ids if cid not in has_cards]
                            if candidates:
                                has_cards.append(random.choice(candidates))

                        elif mutation_type == "remove" and has_cards:
                            has_cards.pop(random.randrange(len(has_cards)))

                        elif mutation_type == "replace" and has_cards:
                            idx = random.randrange(len(has_cards))
                            candidates = [cid for cid in all_card_ids if cid not in has_cards]
                            if candidates:
                                has_cards[idx] = random.choice(candidates)

                        if has_cards:
                            rule.conditions["has_card"] = tuple(has_cards) if len(has_cards) > 1 else has_cards[0]
                        else:
                            rule.conditions.pop("has_card", None)

                elif mutate_type == "leftover_provision_min":
                    rule.conditions["leftover_provision_min"] = random.randint(4, 100)

                new_rules.append(rule)

        return RuleSet(new_rules)


def create_random_rule_set(
    card_pool: pd.DataFrame,
    factions: list[Faction],
    stratagems: list,
    num_rules=100,
):
    """
    Creates a RuleSet consisting of a specified number of randomly generated rules.

    Each rule is generated by randomly selecting a faction and leader from the given list,
    and then building conditions and actions accordingly.

    Args:
        card_pool (pd.DataFrame): DataFrame containing all available cards.
        factions (list[Faction]): List of Faction objects to sample factions and leaders from.
        stratagems (list): List of available stratagems to condition on.
        num_rules (int, optional): Number of rules to generate in the rule set. Defaults to 100.

    Returns:
        RuleSet: A RuleSet object containing the generated list of Rule objects.
    """
    rules = [
        create_random_rule(card_pool, factions, stratagems) for _ in range(num_rules)
    ]
    return RuleSet(rules=rules)


def print_ruleset_with_names(ruleset: RuleSet, card_df: pd.DataFrame) -> None:
    def get_card_name(card_id):
        if card_id in card_df.index:
            return card_df.loc[card_id, "name"]
        return str(card_id)

    def format_card_ids(card_ids):
        if isinstance(card_ids, (list, tuple)):
            return tuple(get_card_name(cid) for cid in card_ids)
        return get_card_name(card_ids)

    lines = []
    for i, rule in enumerate(ruleset.rules):
        cond = {}
        for k, v in rule.conditions.items():
            if k in ("has_card", "not_has_card"):
                cond[k] = format_card_ids(v)
            else:
                cond[k] = v

        action = {}
        for k, v in rule.action.items():
            if k == "add_card":
                action[k] = get_card_name(v)
            else:
                action[k] = v

        cond_str = ", ".join(f"{k}={v!r}" for k, v in cond.items())
        action_str = ", ".join(f"{k}={v!r}" for k, v in action.items())
        lines.append(f"<Rule(conditions={{ {cond_str} }}, action={{ {action_str} }})>")

    print(f"RuleSet with {len(ruleset.rules)} rules:")
    print(
        "\n".join(lines[:10])
        + (
            f"\n... (+{len(ruleset.rules) - 10} more)"
            if len(ruleset.rules) > 10
            else ""
        )
    )



def crossover(parent1: RuleSet, parent2: RuleSet) -> RuleSet:
    length = len(parent1)
    half = length // 2

    first_half = parent1.rules[:half]
    second_half = parent2.rules[-(length - half) :]

    seen = {id(rule) for rule in first_half}
    child_rules = first_half[:]

    for rule in second_half:
        if id(rule) not in seen:
            child_rules.append(rule)
            seen.add(id(rule))

    # Pad if needed
    if len(child_rules) < length:
        for rule in parent2.rules + parent1.rules:
            if id(rule) not in seen:
                child_rules.append(rule)
                seen.add(id(rule))
            if len(child_rules) == length:
                break

    return RuleSet(child_rules)
